facemask_shop/dashboard/orders/forms.py
from django import forms


class FacemaskEditorForm(forms.Form):
    facemask_id = forms.IntegerField(required=True, widget=forms.HiddenInput())
    redirect_url = forms.URLField(required=False, widget=forms.HiddenInput())

facemask_shop/dashboard/orders/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import DetailView
from oscar.apps.dashboard.orders import views as oscar_views
from oscar.core.loading import get_model

from facemask_shop.dashboard.orders.forms import FacemaskEditorForm
from facemask_shop.editor.models import Facemask

Order = get_model('order', 'Order')
Line = get_model('order', 'Line')
LineAttribute = get_model('order', 'LineAttribute')


class OrderListView(oscar_views.OrderListView):
    template_name = 'dashboard/orders/order_list.html'


class OrderDetailView(oscar_views.OrderDetailView):
    template_name = 'dashboard/orders/order_detail.html'


class PdfView(DetailView):
    model = Order
    context_object_name = 'order'

    def get_object(self, queryset=None):
        from oscar.apps.dashboard.orders.views import get_order_for_user_or_404
        return get_order_for_user_or_404(
            self.request.user, self.kwargs['number'])

    def get(self, request, *args, **kwargs):
        order = self.get_object()
        order.create_print_file()
        return HttpResponseRedirect(order.print_file.url)


class LineEditView(oscar_views.LineDetailView):
    template_name = 'dashboard/orders/line_edit.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['facemask'] = self.get_facemask(kwargs.get('object'))
        context_data['original_facemask'] = self.get_facemask(kwargs.get('object'), 'original-mask-image-id')
        context_data.setdefault('facemask_form', FacemaskEditorForm(initial={'redirect_url': self.request.GET.get('redirect_url')}))
        return context_data

    def get_facemask(self, line: Line, attribute='mask-image-id') -> Facemask:
        try:
            mask_image_id = line.attributes.get(type=attribute).value
        except LineAttribute.DoesNotExist:
            return None
        try:
            facemask = Facemask.objects.get(pk=mask_image_id)
        except Facemask.DoesNotExist:
            return None
        return facemask

    def post(self, request, *args, **kwargs):
        line = self.get_object()
        order = line.order
        form = FacemaskEditorForm(request.POST)
        if form.is_valid():
            facemask_id = form.cleaned_data['facemask_id']
            la = line.attributes.get(type='mask-image-id')
            # Save original mask image ID (if not already saved)
            line.attributes.get_or_create(
                type='original-mask-image-id',
                defaults={
                    'value': la.value
                }
            )
            la.value = facemask_id
            la.save()
            # Invalidate order PDF
            order.print_file = None
            order.save()
            redirect_url = form.cleaned_data.get('redirect_url')
            if not redirect_url:
                redirect_url = reverse('dashboard:order-detail', kwargs={'number': order.number})
            return HttpResponseRedirect(redirect_url)
        else:
            context = self.get_context_data(object=line, facemask_form=form)
            return self.render_to_response(context)

facemask_shop/dashboard/orders/templates/dashboard/orders/line_edit.html
{% extends 'oscar/dashboard/layout.html' %}
{% load i18n %}
{% load static %}

{% block title %}
{% blocktrans with number=line.order.number id=line.id%}
Order {{ number }} - Line #{{ id }}
{% endblocktrans %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
    <li>
        <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
    </li>
    <li>
        <a href="{% url 'dashboard:order-list' %}">{% trans "Orders" %}</a>
    </li>
    <li>
        <a href="{% url 'dashboard:order-detail' number=line.order.number %}">#{{ line.order.number }}</a>
    </li>
    <li class="active">{% blocktrans with id=line.id %}Line #{{ id }}{% endblocktrans %}</li>
</ul>
{% endblock %}

{% block headertext %}
{% blocktrans with number=line.order.number id=line.id %}Order #{{ number }} - Line #{{ id }}{% endblocktrans %} ({{ line.product }})
{% endblock %}

{% block dashboard_content %}
<div class="row">
    <div class="col-sm-6">
        <div id="facemask-editor-container" class="item active">
            <div id="facemask-editor"></div>
        </div>
    </div>
    <div class="col-sm-6">
        <ol>
            {% if original_facemask.original_image %}
            <li><a href="{{ original_facemask.original_image.url }}" class="btn btn-default">Download original full image</a></li>
            {% endif %}
            {% if facemask.original_image %}
            <li><a href="{{ facemask.original_image.url }}" class="btn btn-default">Download current full image</a></li>
            {% else %}
            <li>Geen original image! Is dit een face mask me?</li>
            {% endif %}
            <li><input type="file" id="fileUploadInput" class="filestyle" data-input="false" data-buttonText="Kies een afbeelding" data-badge="false"></li>
            <!--    <li><button id="rotateImageButton" class="btn btn-default"><span class="glyphicon glyphicon-repeat" aria-hidden="true"></span> Roteer beeld</button></li>-->
            <li>Verschuif de afbeelding op de juiste plaats met je vinger of muis</li>
            <li><button id="toggleGuides" class="btn btn-default">Guides uitzetten</button></li>
            <!--    <li><button id="handleSelfieButton" class="btn btn-default"><span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span> Start camera</button></li>-->
            <!--    <li><button id="switchCameraButton" class="btn btn-default" disabled><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Wissel camera</button></li>-->
            <!--    <li>Zet je neus en mond op de juiste plaats</li>-->
            <!--    <li><button id="captureSelfieButton" class="btn btn-default" disabled><span class="glyphicon glyphicon-record" aria-hidden="true"></span> Leg foto vast</button></li>-->
            <li><button id="toggleRotationButton" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden="true"></span> Looks good?</button></li>
            <li><button id="saveNewFacemask" class="btn btn-default">Save new facemask</button></li>
        </ol>
    </div>
</div>

<form method="post" id="facemask-editor-form">
    {% csrf_token %}
    {{ facemask_form }}
</form>

{% endblock %}


{% block extrahead %}
{{ block.super }}
<script src="{{ playcanvas_root }}playcanvas-stable.min.js"></script>
<script>
ASSET_PREFIX = "{{ playcanvas_root }}";
SCRIPT_PREFIX = "{{ playcanvas_root }}";
SCENE_PATH = "916290.json";
CONTEXT_OPTIONS = {
    'antialias': true,
    'alpha': false,
    'preserveDrawingBuffer': false,
    'preferWebGl2': true
};
SCRIPTS = [ 31158195, 31131722, 30592936, 30620114, 30628754, 30803527, 30842522, 30932427, 30980131, 30981096, 30989281, 30989768, 30996399, 31153188 ];
CONFIG_FILENAME = "{{ playcanvas_root }}config.json";
INPUT_SETTINGS = {
    useKeyboard: true,
    useMouse: true,
    useGamepads: false,
    useTouch: true
};
pc.script.legacy = false;
PRELOAD_MODULES = [
];
EDITOR_UPLOAD_URL = '{% url 'editor:upload' %}';
</script>
{% endblock %}

{% block extrastyles %}
{{ block.super }}
<link rel="stylesheet" href="{{ playcanvas_root }}styles.css" />
<style>
/* Empty block for PlayCanvas */

.glyphicon {
    font-family: "Glyphicons Halflings" !important;
}

.bootstrap-filestyle {
    display: inline-block;
}

#facemask-editor-container,
#facemask-editor {
    /*width: 570px;*/
    height: 400px;
}

@media only screen and (max-width : 500px) {
    #product_gallery .thumbnail {
        margin-right: -10%;
        margin-left: -10%;
    }
}

video {
    width: 100%;
}
</style>
{% endblock %}

{% block extrascripts %}
{{ block.super }}
<script src="{{ playcanvas_root }}__start__.js"></script>
<script src="{% static "editor/js/bootstrap-filestyle.min.js" %}"></script>
<script>
var facemask_editor_canvas = document.getElementById('application-canvas');
document.getElementById('facemask-editor').appendChild(facemask_editor_canvas);

var app = pc.Application.getApplication();
var guidesEnabled = false;
app.on("start", function () {
    $('#saveNewFacemask').on('click', function(e) {
        // e.preventDefault();

        var editorForm = $('#facemask-editor-form');
        toggleGuides(false);

        uploadFile(EDITOR_UPLOAD_URL, function(err, response) {
            if (!err && response.success) {
                $('#id_facemask_id').val(response.mask_id);
                editorForm.submit();
            } else {
                if (window.Sentry) {
                    if (err instanceof Error) {
                        Sentry.captureException(err);
                    } else {
                        Sentry.captureMessage(err);
                    }
                }
                console.error(err || response);
                alert("Oeps, er ging iets mis bij het opslaan van je masker! Probeer het later opnieuw.");
            }
        });
    });

    $('#fileUploadInput').on('change', handleImageAsSelfie);
    $('#toggleRotationButton').on('click', toggleRotation).on('click', function() {
        $(this).children('.glyphicon')
            .toggleClass('glyphicon-play', !shouldRotate)
            .toggleClass('glyphicon-pause', shouldRotate);
    });
    $('#rotateImageButton').on('click', rotateImage);
    $('#handleSelfieButton, #switchCameraButton')
        .on('click', function() {
            guidesEnabled = true;
            if (window.facingMode === 'user') {
                window.facingMode = 'environment';
            } else {
                window.facingMode = 'user';
            }
        })
        .on('click', handleSelfie)
        .on('click', function() {
            $('#captureSelfieButton').prop('disabled', false);
            $('#switchCameraButton').prop('disabled', false);
        });
    $('#captureSelfieButton').on('click', captureSelfie);
    $('#toggleGuides').on('click', function () {
        guidesEnabled != guidesEnabled;
        toggleGuides(guidesEnabled);
    });
});
</script>
{% endblock %}

facemask_shop/dashboard/orders/templates/dashboard/orders/order_detail.html
{% extends 'oscar/dashboard/orders/order_detail.html' %}
{% load i18n %}
{% load currency_filters %}


{% block order_lines %}
<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th></th>
        <th></th>
        <th>{% trans "Line ID" %}</th>
        <th>{% trans "Quantity" %}</th>
        <th>{% trans "Product" %}</th>
        <th>{% trans "Status" %}</th>
        <th>Thumbnail</th>
        <th>{% trans "Est. dispatch date" %}</th>
        <th>{% trans "Price excl tax (before discounts)" %}</th>
        <th>{% trans "Price inc tax (before discounts)" %}</th>
        <th>{% trans "Actions" %}</th>
    </tr>
    </thead>
    <tbody>
    {% for line in lines %}
    <tr>
        <td>
            <input type="checkbox" name="selected_line" value="{{ line.id }}" />
        </td>
        <td>
            <input type="text" name="selected_line_qty_{{ line.id }}" value="{{ line.quantity }}" size="2" style="width:40px" />
        </td>
        <td><a href="{% url 'dashboard:order-line-detail' number=order.number line_id=line.id %}">#{{ line.id }}</a></td>
        <td>{{ line.quantity }}</td>
        <td>
            {% if line.product %}
            <a href="{% url 'dashboard:catalogue-product' pk=line.product.id %}">{{ line.title }}</a>
            {% else %}
            {{ line.title }}
            {% endif %}
        </td>
        <td>{{ line.status|default:"-" }}</td>
        <td>
            <a href="{% url 'dashboard:order-line-edit' number=order.number line_id=line.id %}"><img class="thumbnail" src="{% url 'order:line-thumbnail' line.id %}"></a>
        </td>
        <td>{{ line.est_dispatch_date|default:"-" }}</td>
        <td class="text-right">{{ line.line_price_before_discounts_excl_tax|currency:order.currency }}</td>
        <td class="text-right">{{ line.line_price_before_discounts_incl_tax|currency:order.currency }}</td>
        <td>
            <a href="{% url 'dashboard:order-line-detail' number=order.number line_id=line.id %}" class="btn btn-info">{% trans "View" %}</a>
            <a href="{% url 'dashboard:order-line-edit' number=order.number line_id=line.id %}" class="btn btn-info">{% trans "Edit" %}</a>
        </td>
    </tr>
    {% endfor %}

    <tr>
        <td colspan="7"></td>
        <th>{% trans "Discount" %}</th>
        <td class="text-right">{{ order.total_discount_excl_tax|currency:order.currency }}</td>
        <td class="text-right">{{ order.total_discount_incl_tax|currency:order.currency }}</td>
        <td></td>
    </tr>
    {% with discounts=order.basket_discounts %}
    {% if discounts %}
    <tr>
        <td colspan="7"></td>
        <th>{% trans "Basket total (excl. discounts)" %}</th>
        <td class="text-right">{{ order.basket_total_before_discounts_excl_tax|currency:order.currency }}</td>
        <td class="text-right">{{ order.basket_total_before_discounts_incl_tax|currency:order.currency }}</td>
        <td></td>
    </tr>
    {% for discount in discounts %}
    <tr>
        <td colspan="7"></td>
        <td>
            <span class="label label-success">{% trans "Discount" %}</span>
            {{ discount.offer_name }}
        </td>
        <td class="text-right"></td>
        <td class="text-right">- {{ discount.amount|currency:order.currency }}</td>
        <td></td>
    </tr>
    {% endfor %}
    <tr>
        <td colspan="7"></td>
        <th>{% trans "Basket total (inc. discounts)" %}</th>
        <th class="text-right">{{ order.basket_total_excl_tax|currency:order.currency }}</th>
        <th class="text-right">{{ order.basket_total_incl_tax|currency:order.currency }}</th>
        <td></td>
    </tr>
    {% else %}
    <tr>
        <td colspan="7"></td>
        <th>{% trans "Basket total" %}</th>
        <th class="text-right">{{ order.basket_total_excl_tax|currency:order.currency }}</th>
        <th class="text-right">{{ order.basket_total_incl_tax|currency:order.currency }}</th>
        <td></td>
    </tr>
    {% endif %}
    {% endwith %}

    {% if order.has_shipping_discounts %}
    <tr>
        <td colspan="7"></td>
        <td>{% trans "Shipping total (excl. discounts)" %}</td>
        <td class="text-right">{{ order.shipping_before_discounts_excl_tax|currency:order.currency }}</td>
        <td class="text-right">{{ order.shipping_before_discounts_incl_tax|currency:order.currency }}</td>
        <td></td>
    </tr>
    {% for discount in order.shipping_discounts %}
    <tr>
        <td colspan="7"></td>
        <td>
            <span class="label label-success">{% trans "Discount" %}</span>
            {{ discount.offer_name }}
        </td>
        <td></td>
        <td class="text-right">- {{ discount.amount|currency:order.currency }}</td>
        <td></td>
    </tr>
    {% endfor %}
    <tr>
        <td colspan="7"></td>
        <th>{% trans "Shipping total (inc. discounts)" %}</th>
        <th class="text-right">{{ order.shipping_excl_tax|currency:order.currency }}</th>
        <th class="text-right">{{ order.shipping_incl_tax|currency:order.currency }}</th>
        <td></td>
    </tr>
    {% else %}
    <tr>
        <td colspan="7"></td>
        <th>{% trans "Shipping total" %}</th>
        <th class="text-right">{{ order.shipping_excl_tax|currency:order.currency }}</th>
        <th class="text-right">{{ order.shipping_incl_tax|currency:order.currency }}</th>
        <td></td>
    </tr>
    {% endif %}

    <tr>
        <td colspan="7"></td>
        <th>{% trans "Order total" %}</th>
        <th class="text-right">{{ order.total_excl_tax|currency:order.currency }}</th>
        <th class="text-right">{{ order.total_incl_tax|currency:order.currency }}</th>
        <td></td>
    </tr>
    </tbody>
</table>
{% endblock order_lines %}

facemask_shop/dashboard/orders/templates/dashboard/orders/order_list.html
{% extends 'oscar/dashboard/orders/order_list.html' %}
{% load currency_filters %}
{% load sorting_tags %}
{% load i18n %}

{% block order_list %}
<table class="table table-striped table-bordered table-hover">
    <caption>
        <h3 class="pull-left"><i class="icon-shopping-cart icon-large"></i>
            {% if search_filters %}
            {% trans "Order Search Results" %}
            {% else %}
            {% trans "All Orders" %}
            {% endif %}
        </h3>
        <div class="pull-right">
            <div class="form-inline">
                <label>{% trans "Download selected orders as a CSV" %}</label>
                <button type="submit" class="btn btn-primary" name="action" value="download_selected_orders" data-loading-text="{% trans 'Submitting...' %}">{% trans "Download" %}</button>
            </div>
        </div>
    </caption>

    <thead>
    <tr>
        <th></th>
        <th>{% anchor 'number' _("Order number") %}</th>
        <th>{% anchor 'total_incl_tax' _("Total inc tax") %}</th>
        <th>{% trans "Number of items" %}</th>
        <th>{% trans "Status" %}</th>
        <th>{% trans "Customer" %}</th>
        <th>{% trans "Shipping address" %}</th>
        <th>{% trans "Billing address" %}</th>
        <th>{% trans "Date of purchase" %}</th>
        <th>Thumbnail</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for order in orders %}
    <tr>
        <td><input type="checkbox" name="selected_order" class="selected_order" value="{{ order.id }}"/></td>
        <td><a href="{% url 'dashboard:order-detail' number=order.number %}">{{ order.number }}</a></td>
        <td>{{ order.total_incl_tax|currency:order.currency }}</td>
        <td>{{ order.num_items }}</td>
        <td>{{ order.status|default:"-" }}</td>
        <td>
            {% if order.guest_email %}
            {{ order.guest_email }}
            {% elif order.user %}
            <a href="{% url 'dashboard:user-detail' pk=order.user.id %}">{{ order.user.get_full_name|default:"-" }}</a>
            {% else %}
            &lt;{% trans "Deleted" %}&gt;
            {% endif %}
        </td>
        <td>{{ order.shipping_address|default:"-" }}</td>
        <td>{{ order.billing_address|default:"-" }}</td>
        <td>{{ order.date_placed }}</td>
        <td>
            {% for line in order.lines.all %}
            <a href="{% url 'dashboard:order-line-edit' number=order.number line_id=line.id %}"><img class="thumbnail" src="{% url 'order:line-thumbnail' line.id %}"></a>
            {% endfor %}
        </td>
        <td>
            <a class="btn btn-info" href="{% url 'dashboard:order-detail' number=order.number %}">{% trans "View" %}</a>
            <a class="btn btn-info" href="{% url 'dashboard:order-pdf' number=order.number %}">PDF</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}